# Dictionary of French verb tuples -- each entry, organized  by the infinitive, contains a tuple organized in this order: 
# 1 - 1st person singular verb 
# 2 - 2nd person singular verb 
# 3 - 1st person singular passé simple  
# 4 - gerund 
# 5 - past participle  
# 6 - avoir | être for compound verbs

verbs = {
    'abaisser': ('abaisse', 'abaisses', 'abaissai', 'abaissant', 'abaissé', 'avoir'),
    'abasourdir': ('abasourdis', 'abasourdis', 'abasourdis', 'abasourdissant', 'abasourdi', 'avoir'),
    'abattre': ('abats', 'abats', 'abbattis', 'abattant', 'abattu', 'avoir'),
    'abolir': ('abolis', 'abolis', 'abolis', 'abolissant', 'aboli', 'avoir'), 
    'absoudre': ('absous', 'absous', 'absolus', 'absolvant', 'absous', 'avoir'), 
    'accorder': ('accorde', 'accordes', 'accordai', 'accordant', 'accordé', 'avoir'), 
    'accourir': ('accours', 'accours', 'accourus', 'accourant', 'accouru', 'avoir'),
    'accrocher': ('accroche', 'accroches', 'accrochai', 'accrochant', 'accroché', 'avoir'),
    'accueillir': ('accueille', 'accueilles', 'accueillis', 'accueillant', 'accueilli', 'avoir'), 
    'acheter': ('achète', 'achètes', 'achetai', 'achetant', 'acheté', 'avoir'), 
    'acquérir': ('acquiers', 'acquiers', 'acquis', 'acquérant', 'acquis', 'avoir'), 
    'admettre': ('admets', 'admets', 'admis', 'admettant', 'admis', 'avoir'),
    'adorer': ('adore', 'adores', 'adorai', 'adorant', 'adoré', 'avoir'),
    'agir': ('agis', 'agis', 'agis', 'agissant', 'agi', 'avoir'),
    'aider': ('aide', 'aides', 'aidai', 'aidant', 'aidé', 'avoir'),
    'aimer': ('aime', 'aimes', 'aimai', 'aimant', 'aimé', 'avoir'), 
    'ajouter': ('ajoute', 'ajoutes', 'ajoutai', 'ajoutant', 'ajouté', 'avoir'),
    'aller': ('vais', 'vas', 'allai', 'allant', 'allé', 'être'),
    'amener': ('amène', 'amènes', 'amenai', 'amenant', 'amené', 'avoir'), 
    'amuser': ('amuse', 'amuses', 'amusai', 'amusant', 'amusé', 'avoir'),
    'annoncer': ('annonce', 'annonces', 'annonçai', 'annonçant', 'annoncé', 'avoir'),
    'apercevoir': ('aperçois', 'aperçois', 'aperçus', 'apercevant', 'aperçu', 'avoir'), 
    'apprendre': ('apprends', 'apprends', 'appris', 'apprenant', 'appris', 'avoir'), 
    'approcher': ('approche', 'approches', 'approchai', 'approchant', 'approché', 'avoir'),
    'approuver': ('approuve', 'approuves', 'approuvai', 'approuvant', 'approuvé', 'avoir'),
    'arrêter': ('arrête', 'arrêtes', 'arrêtai', 'arrêtant', 'arrêté', 'avoir'),
    'arriver': ('arrive', 'arrives', 'arrivai', 'arrivant', 'arrivé', 'être'),
    'atteindre': ('atteins', 'atteins', 'atteignis', 'atteignant', 'atteint', 'avoir'),
    'attendre': ('attends', 'attends', 'attendis', 'attendant', 'attendu', 'avoir'), 
    'avoir': ('ai', 'as', 'eus', 'ayant', 'eu', 'avoir'),
    'balancer': ('balance', 'balances', 'balançai', 'balançant', 'balancé', 'avoir'),
    'battre': ('bats', 'bats', 'battis', 'battant', 'battu', 'avoir'),
    'boire': ('bois', 'bois', 'bus', 'buvant', 'bu', 'avoir'),
    'bouger': ('bouge', 'bouges', 'bougeai', 'bougeant', 'bougé', 'avoir'),
    'brûler': ('brûle', 'brûles', 'brûlai', 'brûlant', 'brûlé', 'avoir'),
    'cacher': ('cache', 'caches', 'cachai', 'cachant', 'caché', 'avoir'),
    'casser': ('casse', 'casses', 'cassai', 'cassant', 'cassé', 'avoir'),
    'causer': ('cause', 'causes', 'causai', 'causant', 'causé', 'avoir'), 
    'cesser': ('cesse', 'cesses', 'cessai', 'cessant', 'cessé', 'avoir'),
    'changer': ('change', 'changes', 'changeai', 'changeant', 'changé', 'avoir'),
    'chercher': ('cherche', 'cherches', 'cherchai', 'cherchant', 'cherché', 'avoir'),
    'choisir': ('choisis', 'choisis', 'choisis', 'choisissant', 'choisi', 'avoir'),
    'comparer': ('compare', 'compares', 'comparai', 'comparant', 'comparé', 'avoir'),
    'comprendre': ('comprends', 'comprends', 'compris', 'comprenant', 'compris', 'avoir'), 
    'compter': ('compte', 'comptes', 'comptai', 'comptant', 'compté', 'avoir'),
    'concevoir': ('conçois', 'conçois', 'conçus', 'concevant', 'conçu', 'avoir'), 
    'conduire': ('conduis', 'conduis', 'conduisis', 'conduisant', 'conduit', 'avoir'), 
    'confondre': ('confonds', 'confonds', 'confondis', 'confondant', 'confondu', 'avoir'), 
    'dire': ('dis', 'dis', 'dis', 'disant', 'dit', 'avoir'), 
    'donner': ('donne', 'donnes', 'donnai', 'donnant', 'donné', 'avoir'),
    'dormir': ('dors', 'dors', 'dormis', 'dormant', 'dormi', 'avoir'),
    'écrire': ('écris', 'écris', 'écrivis', 'écrivant', 'écrit', 'avoir'),
    'élire': ('élis', 'élis', 'élus', 'élisant', 'élu', 'avoir'),
    'emmener': ('emmène', 'emmènes', 'emmenai', 'emmenant', 'emmené', 'avoir'),  
    'émouvoir': ('émeus', 'émeus', 'émus', 'émouvant', 'ému', 'avoir'), 
    'enlever': ('enlève', 'enlèves', 'enlevai', 'enlevant', 'enlevé', 'avoir'), 
    'entrer': ('entre', 'entres', 'entrai', 'entrant', 'entré', 'être'), 
    'envoyer': ('envoie', 'envoies', 'envoyai', 'envoyant', 'envoyé', 'avoir'),
    'espérer': ('espère', 'espères', 'espérai', 'espérant', 'espéré', 'avoir'), 
    'essayer': ('essaye', 'essayes', 'essayai', 'essayant', 'essayé', 'avoir'),
    'être': ('suis', 'es', 'fus', 'étant', 'été', 'avoir'),
    'étudier': ('étudie', 'étudies', 'étudiai', 'étudiant', 'étudié', 'avoir'),
    'éviter': ('évite', 'évites', 'évitai', 'évitant', 'évité', 'avoir'),  
    'faire': ('fais', 'fais', 'fis', 'faisant', 'fait', 'avoir'), 
    'fendre': ('fends', 'fends', 'fendis', 'fendant', 'fendu', 'avoir'),
    'fermer': ('ferme', 'fermes', 'fermai', 'fermant', 'fermé', 'avoir'),
    'fuir': ('fuis', 'fuis', 'fuis', 'fuyant', 'fui', 'avoir'), 
    'fumer': ('fume', 'fumes', 'fumai', 'fumant', 'fumé', 'avoir'), 
    'gagner': ('gagne', 'gagnes', 'gagnai', 'gagnant', 'gagné', 'avoir'),
    'guérir': ('guéris', 'guéris', 'guéris', 'guérissant', 'guéri', 'avoir'),
    'habiter': ('habite', 'habites', 'habitai', 'habitant', 'habité', 'avoir'),
    'hésiter': ('hésite', 'hésites', 'hésitai', 'hésitant', 'hésité', 'avoir'),  
    'imposer': ('impose', 'imposes', 'imposai', 'imposant', 'imposé', 'avoir'), 
    'interrompre': ('interromps', 'interromps', 'interrompis', 'interrompant', 'interrompu', 'avoir'),
    'inviter': ('invite', 'invites', 'invitai', 'invitant', 'invité', 'avoir'),
    'jeter': ('jette', 'jettes', 'jetai', 'jetant', 'jeté', 'avoir'), 
    'joindre': ('joins', 'joins', 'joignis', 'joignant', 'joint', 'avoir'),
    'jouer': ('joue', 'joues', 'jouai', 'jouant', 'joué', 'avoir'),  
    'laver': ('lave', 'laves', 'lavai', 'lavant', 'lavé', 'avoir'), 
    'lever': ('lève', 'lèves', 'levai', 'levant', 'levé', 'avoir'),
    'lire': ('lis', 'lis', 'lus', 'lisant', 'lu', 'avoir'), 
    'louer': ('loue', 'loues', 'louai', 'louant', 'loué', 'avoir'), 
    'lutter': ('lutte', 'luttes', 'luttai', 'luttant', 'lutté', 'avoir'), 
    'manger': ('mange', 'manges', 'mangeai', 'mangeant', 'mangé', 'avoir'),
    'marcher': ('marche', 'marches', 'marchai', 'marchant', 'marché', 'avoir'),
    'marier': ('marie', 'maries', 'mariai', 'mariant', 'marié', 'avoir'), 
    'mettre': ('mets', 'mets', 'mis', 'mettant', 'mis', 'avoir'),
    'monter': ('monte', 'montes', 'montai', 'montant', 'monté', 'être'),
    'mourir': ('meurs', 'meurs', 'mourus', 'mourant', 'mort', 'être'), 
    'naître': ('nais', 'nais', 'naquis', 'naissant', 'né', 'être'),
    'nettoyer': ('nettoie', 'nettoies', 'nettoyai', 'nettoyant', 'nettoyé', 'avoir'),
    'obliger': ('oblige', 'obliges', 'obligeai', 'obligeant', 'obligé', 'avoir'),
    
    
}