# Dictionary of Spanish verb tuples -- each entry, organized  by the infinitive, contains a tuple organized in this order: 
# 1 - 1st person singular verb 
# 2 - 2nd person singular verb 
# 3 - 1st person singular preterite 
# 4 - gerund 
# 5 - past participle tuple


verbs = {
'abalanzarse': ('abalanzo', 'abalanzas', 'abalancé', 'abalanzando', ('abalanzado',)), 
'abandonar': ('abandono', 'abandonas', 'abandoné', 'abandonando', ('abandonado',)), 
'anegar': ('aniego', 'aniegas', 'anegué', 'anegando', ('anegado',)),
'abrir': ('abro', 'abres', 'abrí', 'abriendo', ('abierto',)), 
'aducir': ('aduzco', 'aduces', 'aduje', 'aduciendo', ('aducido',)), 
'alquilar': ('alquilo', 'alquiles', 'alquilé', 'alquilando', ('alquilado',)), 
'amar': ('amo', 'amas', 'amé', 'amando', ('amado',)), 
'aprobar': ('apruebo', 'apruebas', 'aprobé', 'aprobando', ('aprobado',)), 
'atraer': ('atraigo', 'atraes', 'atraje', 'atrayendo', ('atraído')),
'aumentar': ('aumento', 'aumentas', 'aumenté', 'aumentando', ('aumentado',)), 
'averiguar': ('averiguo', 'averiguas', 'averigüé', 'averiguando', ('averiguado',)), 
'bailar': ('bailo', 'bailas', 'bailé', 'bailando', ('bailado',)), 
'bajar': ('bajo', 'bajas', 'bajé', 'bajando', ('bajado',)),
'borrar': ('borro', 'borras', 'borré', 'borrando', ('borrado',)), 
'caber': ('quepo', 'cabes', 'cupe', 'cabiendo', ('cabido',)), 
'caducar': ('caduco', 'caducas', 'caduqué', 'caducando', ('caducado')), 
'caer': ('caigo', 'caes', 'caí', 'cayendo', ('caído',)), 
'cocinar':('cocino', 'cocinas', 'cociné', 'cocinando', ('cocinado',)), 
'comenzar':('comienzo', 'comienzas', 'comencé', 'comenzando', ('comenzado',)), 
'comprar': ('compro', 'compras', 'compré', 'comprando', ('comprado',)), 
'concluir': ('concluyo', 'concluyes', 'concluí', 'concluyendo', ('concluido',)), 
'conducir': ('conduzco', 'conduces', 'conduje', 'conduciendo', ('conducido',)), 
'conocer': ('conozco', 'conoces', 'conocí', 'conociendo', ('conocido',)), 
'contar': ('cuento', 'cuentas', 'conté', 'contando', ('contado',)), 
'contratar': ('contrato', 'contratas', 'contraté', 'contratando', ('contratado',)), 
'convencer': ('convenzo', 'convences', 'convencí', 'convenciendo', ('convencido',)), 
'convenir': ('convengo', 'convienes', 'convine', 'conviniendo', ('convenido',)), 
'crear': ('creo', 'creas', 'creé', 'creando', ('creado',)), 
'creer': ('creo', 'crees', 'creí', 'creyendo', ('creído')), 
'cubrir': ('cubro', 'cubres', 'cubrí', 'cubriendo', ('cubrido',)), 
'dar': ('doy', 'das', 'di', 'dando', ('dado',)), 
'deber': ('debo', 'debes', 'debí', 'debiendo', ('debido',)), 
'decir': ( 'digo', 'dices', 'dije', 'diciendo', ('dicho',)), 
'describir': ('describo', 'describe', 'describí', 'describiendo', ('descrito','descripto')),
'descubrir': ('descubro','descubres','descubrí','descubriendo',('descubierto',)),
'desear': ('deseo', 'deseas', 'deseé', 'deseando', ('deseado',)), 
'despedir': ('despido', 'despides', 'despedí', 'despidiendo', ('despedido',)), 
'dirigir': ('dirijo', 'diriges', 'dirigí', 'dirigiendo', ('dirigido',)), 
'disminuir': ('disminuyo', 'disminuyes', 'disminuí', 'disminuyendo', ('disminuido',)),
'disolver': ('disuelvo', 'disuelves', 'disolví', 'disolviendo', ('disuelto',)), 
'dormir': ('duermo', 'duermes', 'dormí', 'durmiendo', ('dormido',)), 
'echar': ('echo', 'echas', 'eché', 'echando', ('echado',)), 
'embalar': ('embalo','embalas', 'embalé', 'embalando', ('embalado',)), 
'empeorar': ('empeoro', 'empeoras', 'empeorando', ('empeorado',)), 
'emplear': ('empleo', 'empleas', 'empleé', 'empleando', ('empleado',)), 
'enfatizar': ('enfatizo', 'enfatizas', 'enfaticé', 'enfatizando', ('enfatizado',)), 
'entender': ('entiendo', 'entiendes', 'entendí', 'entendiendo', ('entendido',)), 
'entrar': ('entro', 'entras', 'entré', 'entrando', ('entrado',)), 
'entregar': ('entrego', 'entregas', 'entregué', 'entregando', ('entregado',)), 
'enviar': ('envio', 'envias', 'envié', 'enviando', ('enviado',)), 
'envolver': ('envuelvo', 'envuelves', 'envolví','envolviendo',('envuelto',)),  
'escoger': ('escojo','escoges','escogí','escogiendo','escogido'),
'escribir': ('escribo', 'escribes', 'escribí', 'escribiendo', ('escrito',)), 
'escuchar': ('escucho', 'escuchas', 'escuché', 'escuchando', ('escuchado',)), 
'estar': ('estoy', 'estás', 'estuve', 'estando', ('estado',)), 
'evaluar': ('evaluo', 'evaluas', 'evalué', 'evaluando', ('evaluado',)), 
'excluir': ('excluyo', 'excluyes', 'excluí', 'excluyendo', ('excluido',)), 
'exportar': ('exporto', 'exportas', 'exporté', 'exportando', ('exportado',)), 
'fabricar': ('fabrico', 'fabricas', 'fabriqué', 'fabricando', ('fabricado',)), 
'freír': ('frío', 'fries', 'freí', 'friendo', ('frito',)), # tambien freído -- TODO convierte en tuple 
'gustar': ('gusto', 'gustas', 'gusté', 'gustando', ('gustado',)), 
'haber': ('he', 'has', 'hube', 'habiendo', ('habido',)), 
'hacer': ('hizo', 'hices', 'hice', 'haciendo', ('hecho',)), 
'hipotecar': ('hipoteco', 'hipotecas', 'hipotequé', 'hipotecando', ('hipotecado',)), 
'importar': ('importo', 'importas', 'importé', 'importando', ('importado',)), 
'imprimir': ('imprimo', 'imprimes', 'imprimí', 'imprimiendo', ('impreso',)), 
'incluir': ('incluyo', 'incluyes', 'incluí', 'incluyendo', ('incluido',)), 
'informar': ('informo', 'informas', 'informé', 'informando', ('informado',)), 
'involucrar': ('involucro', 'involucras', 'involucré', 'involucrando', ('involucrado',)), 
'ir': ('voy', 'vas', 'fui', 'yendo', ('ido',)), 
'lavar': ('lavo', 'lavas', 'lavé', 'lavando', ('lavado',)), 
'leer': ('leo', 'lees', 'leí', 'leyendo', ('leído',)), 
'levantar': ('levanto', 'levantas', 'levanté', 'levantando', ('levantado',)), 
'llamar': ('llamo', 'llamas', 'llamé', 'llamando', ('llamado',)), 
'llegar': ('llego', 'llegas', 'llegué', 'llegando', ('llegado',)), 
'llenar': ('lleno', 'llenas', 'llené', 'llenando', ('llenado',)), 
'llevar': ('llevo', 'llevas', 'llevé', 'llevando', ('llevado',)), 
'mandar': ('mando', 'mandas', 'mandé', 'mandando', ('mandado',)), 
'manejar': ('manejo', 'manejas', 'manejé', 'manejando', ('manejado',)), 
'mantener': ('mantengo', 'mantienes', 'mantuve', 'manteniendo', ('mantenido',)), 
'matar': ('mato', 'matas', 'maté', 'matando', ('matado',)), 
'medir': ('mido', 'mides', 'medí', 'midiendo' ,('medido',)), 
'mejorar': ('mejoro', 'mejoras', 'mejoré', 'mejorando', ('mejorado',)), 
'mentir': ('miento', 'mientes', 'mentí', 'mintiendo', ('mentido',)), 
'meter': ('meto', 'metes', 'metí', 'metiendo', ('metido',)), 
'mirar': ('miro', 'miras', 'miré', 'mirando', ('mirado',)), 
'morir': ('muero', 'mueres', 'morí', 'muriendo', ('muerto',)), 
'necesitar': ('necesito', 'necesitas', 'necesité', 'necesitando', ('necesitado',)), 
'odiar': ('odio', 'odias', 'odié', 'odiando', ('odiado',)), 
'oír': ('oigo', 'oyes', 'oí' ,('oído',)),
'oponer': ('opongo','opones','opuse','oponiendo',('opuesto',)),  
'pagar': ('pago','pagas','pagué','pagando',('pagado',)), 
'parecer': ('parezco', 'pareces', 'parecí', 'pareciendo', ('parecido',)), 
'pedir': ('pido', 'pides', 'pedí', 'pidiendo', ('pedido',)), 
'pegar': ('pego', 'pegas', 'pegué', 'pegando', ('pegado',)), 
'pensar': ('pienso', 'piensas', 'pensé', 'pensando', ('pensado',)), 
'perdonar': ('perdono', 'perdonas', 'perdoné', 'perdonando', ('perdonado',)), 
'permitir': ('permito', 'permites', 'permití', 'permitiendo', ('permitido',)), 
'pesar': ('peso', 'pesas', 'pesé', 'pesando', ('pesado',)), 
'poder': ('puedo', 'puedes', 'pude', 'pudiendo', ('podido',)), 
'poner': ('pongo', 'pones', 'puse', 'poniendo', ('puesto',)), 
'poseer': ('poseo', 'posees', 'poseí', 'poseyendo', ('poseído',)), # también poseído - TODO convierte en tuple 
'postergar': ('postergo', 'postergas', 'postergué', 'postergando', ('postergado',)), 
'predecir': ('predigo', 'predices', 'predije', 'prediciendo', ('predicho',)), 
'preguntar': ('pregunto', 'preguntas', 'pregunté', 'preguntando', ('preguntado',)),
'preparar': ('preparo', 'preparas', 'preparé', 'preparando', ('preparado',)), 
'prever': ('preveo', 'prevés', 'preví', 'previendo', ('previsto',)), 
'producir': ('produzco', 'produces', 'produje', 'produciendo', ('producido',)), 
'proveer': ('proveo', 'provees', 'proveí', 'proveyendo', ('provisto', 'proveído')), 
'pudrir': ('pudro', 'pudres', 'pudrí', 'pudriendo', ('podrido',)), 
'querer': ('quiero', 'quieres', 'quise', 'queriendo', ('querido',)), 
'quitar': ('quito', 'quitas', 'quité', 'quitando', ('quitado',)),
'redactar': ('redacto', 'redactas', 'redacté', 'redactando', ('redactado',)), 
'reducir': ('reduzco', 'reduces', 'reduje', 'reduciendo', ('reducido',)), 
'relatar': ('relato', 'relatas', 'relaté', 'relatando', ('relatado',)), 
'rendir': ('rindo', 'rindes', 'rendí', 'rindiendo', ('rendido',)), 
'repetir': ('repito', 'repites', 'repetí', 'repitiendo', ('repetido',)),
'resolver': ('resuelvo', 'resuelves', 'resolví', 'resolviendo', ('resuelto', 'resoluto')),
'revisar': ('reviso', 'revisas', 'revisé', 'revisando', ('revisado',)), 
'romper': ('rompo', 'rompes', 'rompí', 'rompiendo', ('roto',)), 
'saber': ('sé', 'sabes', 'supe', 'sabiendo', ('sabido',)), 
'sacar': ('saco', 'sacas', 'saqué', 'sacando', ('sacado',)), 
'salir': ('salgo', 'sales', 'salí', 'saliendo', ('salido')),
'seguir': ('sigo', 'sigues', 'seguí', 'siguiendo' ,('seguido',)), 
'ser': ('soy', 'eres', 'fui', 'siendo', ('sido',)), 
'sentarse': ('siento', 'sientas', 'senté', 'sentándome', ('sentado',)), 
'servir': ('sirvo', 'sirves', 'serví', 'sirviendo', ('servido',)), 
'sobornar': ('soborno', 'sobornas', 'sorborné', 'sobornando', ('sobornado',)), 
'sonreír': ('sonrio', 'sonries', 'sonreí', 'sonriendo', ('sonreido',)), 
'tachar': ('tacho', 'tachas', 'taché', 'tachando', ('tachado',)), 
'tener': ('tengo', 'tienes', 'tuve', 'teniendo' ,('tenido',)), 
'traducir': ('traduzco', 'traduces', 'traduje', 'traduciendo', ('traducido',)),  # TODO: complete the tuple with all forms
'traer': ('traigo', 'traes', 'traje', 'trayendo', ('traído',)),  # TODO: complete the tuple with all forms
'usar': ('uso' ,('usado',)), # TODO FINISH VERB 
'utilizar': ('utilizo', 'utilizas', 'utilicé', 'utilizando', ('utilizado',)), 
'vacar': ('vaco', 'vacas', 'vaqué', 'vacando', ('vacado',)), 
'vaciarse': ('vacío', 'vacías', 'vacié', 'vaciando', ('vaciado',)), 
'vacunar': ('vacuno', 'vacunas', 'vacuné', 'vacunando', ('vacunado',)), 
'vencer': ('venzo', 'vences', 'vencí', 'venciendo', ('vencido',)), 
'vender': ('vendo', 'vendes', 'vendí', 'vendiendo', ('vendido',)), 
'venir': ('vengo', 'vienes', 'vine', 'viniendo', ('venido',)), 
'ver': ('veo', 'ves', 'vi', 'viendo' ,('visto',)), 
'versar': ('verso' ,('versado',)),  # TODO: complete the tuple with all forms
'verificar': ('verifico' ,('verificado',)), 
'volver': ('vuelvo', 'vuelves', 'volver', 'volví', 'volviendo', ('vuelto',)), 
'yapar': ('yapo', 'yapas', 'yapé', 'yapando', ('yapado',)), 
'yuxtaponer': ('yuxtapongo', 'yuxtapones', 'yuxtapuse', 'yuxtaponiendo', ('yuxtapuesto',)),
'zafar': ('zafo', 'zafas', 'zafé', 'zafando', ('zafado',)), 
'zaherir': ('zahiero', 'zahieres', 'zaherí', 'zahiriendo', ('zaherido',)), 
'zambullir': ('zambullo', 'zambulles', 'zambullí', 'zambullendo', ('zambullido',)), 
'zampar': ('zampo', 'zampas', 'zampé', 'zampando', ('zampado',)),
}
    