# Dictionary of Portuguese verb tuples -- each entry, organized  by the infinitive, contains a tuple organized in this order: 
# 1 - 1st person singular verb 
# 2 - 2nd person singular verb 
# 3 - 1st person singular preterite 
# 4 - gerund 
# 5 - tuple of past participles  

verbs = {
    'abaixar': ('abaixo', 'abaixas', 'abaixei', 'abaixando', ('abaixado')),
    'abandonar': ('abandono', 'abandonas', 'abandonei', 'abandonando', ('abandonado')),
    'abrir': ('abro', 'abres', 'abri', 'abrindo', ('aberto')), 
    'aceitar': ('aceito', 'aceitas', 'aceitei', 'aceitado', ('aceitado', 'aceite', 'aceito')), 
    'acender': ('acendo', 'acendes', 'acendi', 'acendendo', ('acendido', 'aceso')), 
    'acordar': ('acordo', 'acordas', 'acordei', 'acordando', ('acordado')),
    'acumular': ('acumulo', 'acumulas', 'acumulei', 'acumulando', ('acumulado')),
    'admitir': ('admito', 'admites', 'admiti', 'admitindo', ('admitido')), 
    'advertir': ('advirto', 'advertes', 'adverti', 'avertindo', ('advertido')),
    'afastar': ('afasto', 'afastas', 'afastei', 'afastando', ('afastado')),
    'afligir': ('aflijo', 'afliges', 'afligi', 'afligindo', ('afligido', 'aflito')), 
    'afogar': ('afogo', 'afogas', 'afoguei', 'afogando', ('afogado')),
    'andar': ('ando', 'andas', 'andei', 'andando', ('andado')), 
    'aplaudir': ('aplaudo', 'aplaudes', 'aplaudi', 'aplaudindo', ('aplaudido')),  
    'aprender': ('aprendo', 'aprendes', 'aprendi', 'aprendendo', ('aprendido')), 
    'assistir': ('assisto', 'assistes', 'assisti', 'assistindo', ('assistido')), 
    'atender': ('atendo', 'atendes', 'atendi', 'atendendo', ('atendido')), 
    'bastar': ('basto', 'bastas', 'bastei', 'bastando', ('bastado')),
    'bater': ('bato', 'bates', 'bati', 'batendo', ('batido')), 
    'brincar': ('brinco', 'brincas', 'brinquei', 'brincando', ('brincado')),
    'caminhar': ('caminho', 'caminhas', 'caminhei', 'caminhando', ('caminhado')),
    'cancelar': ('cancelo', 'cancelas', 'cancelei', 'cancelando', ('cancelado')), 
    'chamar': ('chamo', 'chamas', 'chamei', 'chamando', ('chamado')),
    'chocar': ('choco', 'chocas', 'choquei', 'chocando', ('chocado')),
    'comer': ('como', 'comes', 'comi', 'comendo', ('comido')), 
    'contemplar': ('contemplo', 'contemplas', 'contemplei', 'contemplando', ('contemplado')), 
    'cortar': ('corto', 'cortas', 'cortei', 'cortando', ('cortado')), 
    'cuspir': ('cuspo', 'cospes', 'cuspi', 'cuspindo', ('cuspido')),
    'decidir': ('decido', 'decides', 'decidi', 'decidindo', ('decidido')), 
    'deitar': ('deito', 'deitas', 'deitei', 'deitando', ('deitado')),
    'discutir': ('discuto', 'discutes', 'discuti', 'discutindo', ('discutido')),
    'eliminar': ('elimino', 'eliminas', 'eliminei', 'eliminando', ('eliminado')), 
    'entrar': ('entro', 'entras', 'entrei', 'entrando', ('entrado')), 
    'entregar': ('entrego', 'entregas', 'entreguei', 'entregando', ('entregado', 'entregue')), 
    'enxugar': ('enxugo', 'enxugas', 'enxuguei', 'enxugando', ('enxugado', 'enxuto')), 
    'escrever': ('escrevo', 'escreves', 'escrevi', 'escrevendo', ('escrito')), 
    'explicar': ('explico', 'explicas', 'expliquei', 'explicando', ('explicado')),
    'expulsar': ('expulso', 'expulsas', 'expulsei', 'expulsando', ('expulsado', 'expulso')), 
    'falar': ('falo', 'falas', 'falei', 'falando', ('falado')), 
    'fazer': ('faço', 'fazes', 'fiz', 'fazendo', ('feito')),
    'fechar': ('fecho', 'fechas', 'fechei', 'fechando', ('fechado')),
    'fender': ('fendo', 'fendes', 'fendi', 'fendendo', ('fendido', 'fenso')), 
    'ferver': ('fervo', 'ferves', 'fervi', 'fervendo', ('fervido', 'fervente')), 
    'ganhar': ('ganho', 'ganhas', 'ganhei', 'ganhando', ('ganho')), 
    'gastar': ('gasto', 'gastas', 'gastei', 'gastando', ('gasto')), 
    'gerar': ('gero', 'geras', 'gerei', 'gerando', ('gerado')),
    'gostar': ('gosto', 'gostas', 'gostei', 'gostando', ('gostado')),
    'governar': ('governo', 'governas', 'governei', 'governando', ('governado')),
    'habituar': ('habituo', 'habituas', 'habituei', 'habituando', ('habituado')),
    'indicar': ('indico', 'indicas', 'indiquei', 'indicando', ('indicado')),
    'invadir': ('invado', 'invades', 'invadi', 'invadindo', ('invadido')),
    'ir': ('vou', 'vais', 'fui', 'indo', ('ido')),
    'jantar': ('janto', 'jantas', 'jantei', 'jantando', ('jantado')),
    'jogar': ('jogo', 'jogas', 'joguei', 'jogando', ('jogado')),  
    'jurar': ('juro', 'juras', 'jurei', 'jurando', ('jurado')),
    'lavar': ('lavo', 'lavas', 'lavei', 'lavando', ('lavado')), 
    'ler': ('leio', 'lês', 'li', 'lendo', ('lido')),
    'levantar': ('levanto', 'levantas', 'levantei', 'levantando', ('levantado')),
    'levar': ('levo', 'levas', 'levei', 'levando', ('levado')),
    'limpar': ('limpo', 'limpas', 'limpei', 'limpando', ('limpado', 'limpo')), 
    'matar': ('mato', 'matas', 'matei', 'matando', ('matado', 'morto')),
    'meter': ('meto', 'metes', 'meti', 'metendo', ('metido')), 
    'mostrar': ('mostro', 'mostras', 'mostrei', 'mostrando', ('mostrado')),
    'notar': ('noto', 'notas', 'notei', 'notando', ('notado')), 
    'odiar': ('odeio', 'odeias', 'odiei', 'odiando', ('odiado')),
    'omitir': ('omito', 'omites', 'omiti', 'omitindo', ('omitido', 'omisso')), 
    'pagar': ('pago', 'pagas', 'paguei', 'pagando', ('pago')), 
    'prender': ('prendo', 'prendes', 'prendi', 'prendendo', ('prendido', 'preso')),
    'proteger': ('protejo', 'proteges', 'protegi', 'protegendo', ('protegido')), 
    'provar': ('provo', 'provas', 'provei', 'provando', ('provado')),
    'pular': ('pulo', 'pulas', 'pulei', 'pulando', ('pulado')),
    'puxar': ('puxo', 'puxas', 'puxei', 'puxando', ('puxado')),
    'queimar': ('queimo', 'queimas', 'queimei', 'queimando', ('queimado')),
    'querer': ('quero', 'queres', 'quis', 'querendo', ('querido')),
    'responder': ('respondo', 'respondes', 'respondi', 'respondendo', ('respondido')),  
    'romper': ('rompo', 'rompes', 'rompi', 'rompendo', ('rompido', 'roto')), 
    'sentir': ('sinto', 'sentes', 'senti', 'sentindo', ('sentido')), 
    'soltar': ('solto', 'soltas', 'soltei', 'soltando', ('soltado', 'solto')), 
    'subir': ('subo', 'sobes', 'subi', 'subindo', ('subido')), 
    'surpreender': ('surpreendo', 'surpreendes', 'surpreendi', 'surpreendendo', ('surpreendido')), 
    'suspender': ('suspendo', 'suspendes', 'suspendi', 'suspendendo', ('suspendido', 'suspenso')),  
    'transmitir': ('transmito', 'transmites', 'transmiti', 'transmitindo', ('transmitido')), 
    'unir': ('uno', 'unes', 'uni', 'unindo', ('unido')), 
    'vender': ('vendo', 'vendes', 'vendi', 'vendendo', ('vendido')), 
    'ver': ('vejo', 'vês', 'vi', 'vendo', ('visto')), 
    'vestir': ('visto', 'vestes', 'vesti', 'vestindo', ('vestido')),
    'viajar': ('viajo', 'viajas', 'viajei', 'viajando', ('viajado')),  
    'vir': ('venho', 'vens', 'vim', 'vindo', ('vindo')),
    'virar': ('viro', 'viras', 'virei', 'virando', ('virado')),
    'visitar': ('visito', 'visitas', 'visitei', 'visitando', ('visitado')),
    'viver': ('vivo', 'vives', 'vivi', 'vivendo', ('vivido')), 
    'voar': ('voo', 'voas', 'voei', 'voando', ('voado')),
    'voltar': ('volto', 'voltas', 'voltei', 'voltando', ('voltado')),
    'votar': ('voto', 'votas', 'votei', 'votando', ('votado')),
    'zangar': ('zango', 'zangas', 'zanguei', 'zangando', ('zangado'))

    

}